[package]
name = "rust_Practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tungstenite = "0.15"
url = "2.2"
notify-rust = "4.9.0"
screenshots = "0.8.4"
reqwest = { version = "0.11", features = ["multipart"] }



