[package]
name = "rust_Practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.22"
serde_json = "1.0.108"