[package]
name = "rust_Practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
serde_json = "1.0.108"
tokio = { version = "1", features = ["full"] }
screenshots = "0.8.4"
reqwest = { version = "0.11", features = ["multipart"] }


